# Generated by Django 6.0.1 on 2026-02-21 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxpolicy_alter_user_id_document_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential House/Apartment'), ('BOARDING', 'Student Boarding House'), ('LODGE', 'Lodge/Short-stay')], default='RESIDENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(default='Lusaka', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
