# Generated by Django 6.0.2 on 2026-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
