# Generated by Django 6.0.2 on 2026-03-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("TENANT", "Tenant/Seeker"),
                    ("LANDLORD", "Landlord/Property Owner"),
                    ("ZRA", "ZRA Tax Official"),
                    ("MINISTRY", "Ministry of Home Affairs"),
                ],
                default="TENANT",
                max_length=20,
            ),
        ),
    ]
