# Generated by Django 6.0.2 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="apartment_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
