# Generated by Django 6.0.3 on 2026-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_property_apartment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nrc_number',
            field=models.CharField(blank=True, default=234567631, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='tpin_number',
            field=models.PositiveIntegerField(blank=True, default=2345678990),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TENANT', 'Tenant/Seeker'), ('LANDLORD', 'Landlord/Property Owner'), ('ZRA', 'ZRA Tax Official'), ('MINISTRY', 'Ministry of Home Affairs'), ('ADMIN', 'Administrator')], default='TENANT', max_length=20),
        ),
    ]
