# core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Sum, Count, Q
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.authtoken.models import Token

from .models import Property, RentalAgreement, User, Expense
from .serializers import PropertySerializer, RentalAgreementSerializer, ExpenseSerializer

"""
export_views.py  —  Drop these functions into your Django views.py
─────────────────────────────────────────────────────────────────
Endpoints:
  GET /zra/export/pdf/      → streams PDF
  GET /zra/export/excel/    → streams XLSX
  GET /dashboard/export/pdf/    → Landlord PDF
  GET /dashboard/export/excel/  → Landlord XLSX
  GET /ministry/export/pdf/     → Ministry PDF
  GET /ministry/export/excel/   → Ministry XLSX

All exports reflect the same queryset used in the UI view, so
filters you add there (e.g. ?district=Lusaka) can be re-used.
"""
import io, datetime
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET

# ── internal import (your real models) ──
# from .models import Property, RentalApplication, Expense

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame,
    Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfgen import canvas as rl_canvas

# ══════════════════════════════════════════════════════════════════
# SHARED HELPERS
# ══════════════════════════════════════════════════════════════════

NOW = datetime.datetime.now

C = dict(
    primary    = colors.HexColor('#4f46e5'),
    primary_lt = colors.HexColor('#ede9fe'),
    success    = colors.HexColor('#10b981'),
    success_lt = colors.HexColor('#d1fae5'),
    warning    = colors.HexColor('#f59e0b'),
    slate_900  = colors.HexColor('#0f172a'),
    slate_700  = colors.HexColor('#334155'),
    slate_500  = colors.HexColor('#64748b'),
    slate_200  = colors.HexColor('#e2e8f0'),
    slate_100  = colors.HexColor('#f1f5f9'),
    slate_50   = colors.HexColor('#f8fafc'),
    white      = colors.white,
    dark_green = colors.HexColor('#064e3b'),
)
HEX = dict(
    primary='4F46E5', primary_lt='EDE9FE',
    success='10B981', success_lt='D1FAE5',
    warning='F59E0B',
    sl50='F8FAFC', sl100='F1F5F9', sl200='E2E8F0',
    sl700='334155', sl900='0F172A',
    white='FFFFFF', dark_green='064E3B',
)


def _solid(hex_): return PatternFill("solid", fgColor=hex_)
def _brd(color, s='thin'):
    sd = Side(style=s, color=color)
    return Border(left=sd, right=sd, top=sd, bottom=sd)
def _mid_top(color):
    return Border(
        top=Side(style='medium', color=color),
        left=Side(style='thin', color=HEX['sl200']),
        right=Side(style='thin', color=HEX['sl200']),
    )


# ── PDF chrome drawn on every page ──────────────────────────────
def _draw_chrome(canv, doc, portal_label):
    w, h = doc.pagesize
    canv.setFillColor(C['primary'])
    canv.rect(0, h - 16*mm, w, 16*mm, fill=1, stroke=0)
    canv.setFillColor(C['success'])
    canv.rect(0, h - 17*mm, w, 1*mm, fill=1, stroke=0)
    canv.setFont('Helvetica-Bold', 11)
    canv.setFillColor(C['white'])
    canv.drawString(15*mm, h - 10*mm, 'ZAMBIA RENTALS SYSTEM')
    canv.setFont('Helvetica', 8)
    canv.setFillColor(colors.HexColor('#c7d2fe'))
    canv.drawRightString(w - 15*mm, h - 10*mm, portal_label)


# ── Numbered canvas for page X of Y ─────────────────────────────
class _NumCanvas(rl_canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved = []

    def showPage(self):
        self._saved.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._saved)
        for state in self._saved:
            self.__dict__.update(state)
            self._footer(n)
            super().showPage()
        super().save()

    def _footer(self, n):
        w, h = self._pagesize
        ts = NOW().strftime('%d %b %Y  %H:%M')
        self.setFillColor(C['slate_100'])
        self.rect(0, 0, w, 9*mm, fill=1, stroke=0)
        self.setFont('Helvetica', 7)
        self.setFillColor(C['slate_500'])
        self.drawString(15*mm, 3*mm,
            f"Generated by Zambia Rentals System  |  {ts}  |  Confidential")
        self.drawRightString(w - 15*mm, 3*mm, f"Page {self._pageNumber} of {n}")


def _make_doc(buf, pagesize, portal_label):
    doc = BaseDocTemplate(
        buf, pagesize=pagesize,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=20*mm, bottomMargin=13*mm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='body')
    doc.addPageTemplates([PageTemplate(
        id='main', frames=[frame],
        onPage=lambda c, d: _draw_chrome(c, d, portal_label),
    )])
    return doc


def _ps(name, **kw): return ParagraphStyle(name, **kw)


# ── Excel banner row ─────────────────────────────────────────────
def _xl_banner(ws, title, sub, ncols, date_str):
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=ncols)
    c = ws['A1']
    c.value     = f"ZAMBIA RENTALS SYSTEM — {title.upper()}"
    c.font      = Font(bold=True, size=14, color=HEX['white'], name='Arial')
    c.fill      = _solid(HEX['primary'])
    c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 30

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=ncols)
    c = ws['A2']
    c.value     = sub + f"     Generated: {date_str}"
    c.font      = Font(italic=True, size=9, color=HEX['sl700'], name='Arial')
    c.fill      = _solid(HEX['primary_lt'])
    c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[2].height = 15
    ws.row_dimensions[3].height = 8


def _xl_header_row(ws, cols, row_n):
    for ci, h in enumerate(cols, 1):
        c = ws.cell(row=row_n, column=ci, value=h)
        c.font      = Font(bold=True, size=9, color=HEX['white'], name='Arial')
        c.fill      = _solid(HEX['primary'])
        c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        c.border    = Border(bottom=Side(style='medium', color=HEX['success']))
    ws.row_dimensions[row_n].height = 28


# ══════════════════════════════════════════════════════════════════
#  ZRA EXPORTS  —  Turnover Tax Registry
# ══════════════════════════════════════════════════════════════════

def _get_zra_data(request):
    """
    Returns filtered dynamic data from the database.
    Includes TPIN and NRC for Landlords.
    """
    from .models import Property, TaxPolicy

    # Use the same logic as PropertyViewSet.get_queryset
    queryset = Property.objects.all().select_related('owner')

    status_filter = request.GET.get('status')
    search = request.GET.get('search')

    if status_filter == 'pending':
        queryset = queryset.filter(is_tax_compliant=False)
    elif status_filter == 'compliant':
        queryset = queryset.filter(is_tax_compliant=True)

    if search:
        queryset = queryset.filter(
            Q(title__icontains=search) |
            Q(owner__full_name__icontains=search) |
            Q(owner__username__icontains=search) |
            Q(owner__tpin_number__icontains=search) |
            Q(owner__nrc_number__icontains=search) |
            Q(id__icontains=search)
        )

    policy = TaxPolicy.objects.first()
    rate = float(policy.percentage) / 100.0 if policy else 0.10

    data = []
    for prop in queryset:
        rent = float(prop.price)
        apts = prop.apartment_count
        total = rent * apts * 12 # Annual
        tax = float(prop.estimated_annual_tax())
        data.append({
            'landlord': prop.owner.full_name or prop.owner.username,
            'tpin': prop.owner.tpin_number or 'N/A',
            'nrc': prop.owner.nrc_number or 'N/A',
            'id': prop.pk,
            'apartments': apts,
            'rent': rent,
            'total': total,
            'rate': rate,
            'tax': tax,
            'after_tax': total - tax,
        })
    return data


@require_GET
@login_required
def zra_export_pdf(request):
    data     = _get_zra_data(request)
    date_str = NOW().strftime('%d %B %Y')
    rpt_id   = NOW().strftime('TTR-%Y%m%d%H%M')
    buf      = io.BytesIO()

    doc   = _make_doc(buf, landscape(A4), 'ZRA Official Portal')
    pw    = doc.width
    story = []

    # ── Title ──
    story += [
        Paragraph("Turnover Tax Report",
                  _ps('t', fontName='Helvetica-Bold', fontSize=22,
                      textColor=C['primary'], spaceAfter=3, leading=26)),
        Paragraph(f"Generated on: {date_str}&nbsp;&nbsp;&nbsp;Report ID: {rpt_id}",
                  _ps('s', fontName='Helvetica', fontSize=9,
                      textColor=C['slate_500'], spaceAfter=2)),
        HRFlowable(width='100%', thickness=1, color=C['primary_lt'], spaceAfter=6),
    ]

    # ── KPI cards ──
    tot_r = sum(r['total']     for r in data)
    tot_t = sum(r['tax']       for r in data)
    tot_a = sum(r['after_tax'] for r in data)

    def _kpi(lbl, val, col):
        return [
            Paragraph(lbl, _ps('kl', fontName='Helvetica', fontSize=7.5,
                               textColor=C['slate_500'], alignment=TA_CENTER,
                               spaceAfter=2)),
            Paragraph(val, _ps('kv', fontName='Helvetica-Bold', fontSize=15,
                               textColor=col, alignment=TA_CENTER, leading=18)),
        ]

    kd = [[
        _kpi("Total Landlords",     str(len(data)),                C['primary']),
        _kpi("Total Revenue",       f"ZMW {tot_r:,.2f}",          C['success']),
        _kpi("Total Tax Collected", f"ZMW {tot_t:,.2f}",          C['warning']),
        _kpi("Net After Tax",       f"ZMW {tot_a:,.2f}",          C['slate_700']),
    ]]
    kt = Table(kd, colWidths=[pw/4]*4, rowHeights=[16*mm])
    kt.setStyle(TableStyle([
        ('BACKGROUND', (0,0),(-1,-1), C['slate_50']),
        ('BOX',        (0,0),(-1,-1), 0.5, C['slate_200']),
        ('INNERGRID',  (0,0),(-1,-1), 0.5, C['slate_200']),
        ('VALIGN',     (0,0),(-1,-1), 'MIDDLE'),
        ('ALIGN',      (0,0),(-1,-1), 'CENTER'),
    ]))
    story += [kt, Spacer(1, 6*mm)]

    # ── Section label ──
    story.append(Paragraph("DETAILED REGISTRY",
        _ps('sec', fontName='Helvetica-Bold', fontSize=8,
            textColor=C['slate_700'], spaceBefore=4, spaceAfter=5, letterSpacing=1)))

    # ── Data table ──
    HDR = ["Landlord Name", "TPIN", "NRC", "ID", "Apts", "Rent (ZMW)",
           "Total (ZMW)", "Rate", "Tax (ZMW)", "Net (ZMW)"]
    rows = [[
        r['landlord'], r['tpin'], r['nrc'], str(r['id']), str(r['apartments']),
        f"{r['rent']:,.2f}", f"{r['total']:,.2f}",
        f"{r['rate']*100:.1f}%",
        f"{r['tax']:,.2f}", f"{r['after_tax']:,.2f}",
    ] for r in data]
    rows.append([
        "TOTALS", "", "", "", str(sum(r['apartments'] for r in data)),
        "", f"{tot_r:,.2f}", "", f"{tot_t:,.2f}", f"{tot_a:,.2f}",
    ])
    nd = len(rows) - 1

    # Total width is ~267mm in landscape A4 (297 - 30 margins)
    col_w = [42*mm, 28*mm, 28*mm, 14*mm, 14*mm, 28*mm, 30*mm, 18*mm, 28*mm, 30*mm]
    tbl   = Table([HDR]+rows, colWidths=col_w, repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0),  C['primary']),
        ('TEXTCOLOR',     (0,0), (-1,0),  C['white']),
        ('FONTNAME',      (0,0), (-1,0),  'Helvetica-Bold'),
        ('FONTSIZE',      (0,0), (-1,0),  7.5),
        ('ALIGN',         (0,0), (-1,0),  'CENTER'),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
        ('RIGHTPADDING',  (0,0), (-1,-1), 6),
        ('FONTNAME',      (0,1), (-1,-2), 'Helvetica'),
        ('FONTSIZE',      (0,1), (-1,-2), 8),
        ('TEXTCOLOR',     (0,1), (-1,-2), C['slate_700']),
        ('ROWBACKGROUNDS',(0,1), (-1,-2), [C['white'], C['slate_50']]),
        ('LINEBELOW',     (0,0), (-1,-2), 0.4, C['slate_200']),
        ('ALIGN',         (4,1), (-1,-2),  'RIGHT'),
        ('ALIGN',         (7,1), (7,-2),  'CENTER'),
        ('TEXTCOLOR',     (8,1), (8,-2),  C['warning']),
        ('FONTNAME',      (8,1), (8,-2),  'Helvetica-Bold'),
        ('TEXTCOLOR',     (9,1), (9,-2),  C['success']),
        ('FONTNAME',      (9,1), (9,-2),  'Helvetica-Bold'),
        ('BACKGROUND',    (0,nd+1),(-1,nd+1), C['dark_green']),
        ('TEXTCOLOR',     (0,nd+1),(-1,nd+1), C['white']),
        ('FONTNAME',      (0,nd+1),(-1,nd+1), 'Helvetica-Bold'),
        ('FONTSIZE',      (0,nd+1),(-1,nd+1), 8),
        ('ALIGN',         (4,nd+1),(-1,nd+1), 'RIGHT'),
        ('LINEABOVE',     (0,nd+1),(-1,nd+1), 1.5, C['success']),
        ('VALIGN',        (0,0),  (-1,-1),    'MIDDLE'),
    ]))
    story.append(tbl)
    story += [
        Spacer(1, 5*mm),
        Paragraph(
            "All amounts are in Zambian Kwacha (ZMW). "
            "This report is generated by the Zambia Rentals System and is intended for official use only.",
            _ps('fn', fontName='Helvetica', fontSize=7.5,
                textColor=C['slate_500'], leading=11)
        )
    ]

    doc.build(story, canvasmaker=_NumCanvas)
    buf.seek(0)
    fname = f"ZRA_Turnover_Tax_{NOW().strftime('%Y-%m-%d')}.pdf"
    resp  = HttpResponse(buf, content_type='application/pdf')
    resp['Content-Disposition'] = f'attachment; filename="{fname}"'
    return resp


@require_GET
@login_required
def zra_export_excel(request):
    data     = _get_zra_data(request)
    date_str = NOW().strftime('%d %B %Y')
    rpt_id   = NOW().strftime('TTR-%Y%m%d%H%M')

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Turnover Tax Report"

    _xl_banner(ws, "Turnover Tax Report",
               f"ZRA Official Portal     Report ID: {rpt_id}", 8, date_str)

    # ── KPI block (rows 4-6) ──
    tots = [len(data),
            sum(r['total'] for r in data),
            sum(r['tax']   for r in data),
            sum(r['after_tax'] for r in data)]
    kpi_labels = ["Total Landlords","Total Revenue (ZMW)","Tax Collected (ZMW)","Net After Tax (ZMW)"]
    kpi_cols   = [HEX['primary'], HEX['success'], HEX['warning'], HEX['sl900']]
    for i, (lbl, val, col) in enumerate(zip(kpi_labels, tots, kpi_cols)):
        sc = i * 2 + 1
        for row_n in (4, 5, 6):
            ws.merge_cells(start_row=row_n, start_column=sc, end_row=row_n, end_column=sc+1)
        c4 = ws.cell(row=4, column=sc, value=lbl)
        c4.font=Font(size=8,color=HEX['sl700'],name='Arial'); c4.fill=_solid(HEX['sl100'])
        c4.alignment=Alignment(horizontal='center',vertical='center')
        ws.row_dimensions[4].height=14

        c5 = ws.cell(row=5, column=sc, value=val)
        c5.font=Font(bold=True,size=14,color=col,name='Arial'); c5.fill=_solid(HEX['sl50'])
        c5.alignment=Alignment(horizontal='center',vertical='center')
        if i > 0: c5.number_format='"ZMW "#,##0.00'
        ws.row_dimensions[5].height=24
        ws.row_dimensions[6].height=8

    # ── Header row (row 7) ──
    COLS = ["Landlord Name", "TPIN", "NRC", "ID", "Apts", "Rent Amount",
            "Total Amount", "Tax Rate", "Tax Amount", "Amount after Tax"]
    HDR_ROW = 7
    _xl_header_row(ws, COLS, HDR_ROW)

    # ── Data rows ──
    DS = HDR_ROW + 1
    for ri, r in enumerate(data):
        rn   = DS + ri
        fill = HEX['white'] if ri % 2 == 0 else HEX['sl50']
        vals = [r['landlord'], r['tpin'], r['nrc'], r['id'], r['apartments'],
                r['rent'], r['total'], r['rate'], r['tax'], r['after_tax']]
        for ci, val in enumerate(vals, 1):
            c = ws.cell(row=rn, column=ci, value=val)
            c.font   = Font(size=9, name='Arial', color=HEX['sl700'])
            c.fill   = _solid(fill)
            c.border = _brd(HEX['sl200'])
            c.alignment = Alignment(
                horizontal='center' if ci in (2,3,4) else 'right' if ci in (5,6,7,9,10) else 'left',
                vertical='center')
            if ci in (6,7,9,10): c.number_format='"ZMW "#,##0.00'
            elif ci==8:          c.number_format='0.0%'
            if ci==9: c.font=Font(size=9,name='Arial',color=HEX['warning'],bold=True)
            if ci==10: c.font=Font(size=9,name='Arial',color=HEX['success'],bold=True)
        ws.row_dimensions[rn].height = 18

    # ── Totals row ──
    TROW = DS + len(data)
    for ci, (val, align, col, fmt) in enumerate([
        ("TOTALS","left", HEX['white'],False),
        ("","center",     HEX['white'],False),
        ("","center",     HEX['white'],False),
        ("","center",     HEX['white'],False),
        (f'=SUM(E{DS}:E{TROW-1})',"right",HEX['white'],False),
        ("","right",      HEX['white'],False),
        (f'=SUM(G{DS}:G{TROW-1})',"right",HEX['white'],True),
        ("","center",     HEX['white'],False),
        (f'=SUM(I{DS}:I{TROW-1})',"right",HEX['warning'],True),
        (f'=SUM(J{DS}:J{TROW-1})',"right",HEX['success'],True),
    ], 1):
        c=ws.cell(row=TROW,column=ci,value=val)
        c.font=Font(bold=True,size=9,name='Arial',color=col)
        c.fill=_solid(HEX['dark_green'])
        c.alignment=Alignment(horizontal=align,vertical='center')
        c.border=_mid_top(HEX['success'])
        if fmt: c.number_format='"ZMW "#,##0.00'
    ws.row_dimensions[TROW].height=22

    for i,w in enumerate([30,16,16,10,10,18,20,10,20,22],1):
        ws.column_dimensions[get_column_letter(i)].width=w
    ws.freeze_panes=f"A{DS}"
    ws.auto_filter.ref=f"A{HDR_ROW}:H{TROW-1}"
    ws.page_setup.orientation=ws.ORIENTATION_LANDSCAPE
    ws.page_setup.paperSize=ws.PAPERSIZE_A4
    ws.page_setup.fitToWidth=1
    ws.print_title_rows=f"$1:${HDR_ROW}"
    ws.sheet_view.showGridLines=False

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    fname = f"ZRA_Turnover_Tax_{NOW().strftime('%Y-%m-%d')}.xlsx"
    resp  = HttpResponse(buf,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    resp['Content-Disposition'] = f'attachment; filename="{fname}"'
    return resp


# ══════════════════════════════════════════════════════════════════
# MINISTRY EXPORTS  —  District Occupancy
# ══════════════════════════════════════════════════════════════════

def _get_ministry_data(request):
    # Replace with: RentalApplication.objects.values('property__district')
    #               .annotate(total_people=Sum('number_of_occupants'),
    #                         property_count=Count('property',distinct=True))
    return [
        {"district":"Lusaka",      "total_people":312,"property_count":48,"density":"HIGH"},
        {"district":"Kitwe",       "total_people":198,"property_count":31,"density":"HIGH"},
        {"district":"Ndola",       "total_people":145,"property_count":24,"density":"MED"},
        {"district":"Livingstone", "total_people":87, "property_count":14,"density":"MED"},
        {"district":"Kabwe",       "total_people":54, "property_count":9, "density":"MED"},
        {"district":"Chipata",     "total_people":32, "property_count":5, "density":"LOW"},
        {"district":"Solwezi",     "total_people":18, "property_count":3, "density":"LOW"},
    ]


@require_GET
@login_required
def ministry_export_pdf(request):
    data     = _get_ministry_data(request)
    date_str = NOW().strftime('%d %B %Y')
    rpt_id   = NOW().strftime('MOC-%Y%m%d%H%M')
    buf      = io.BytesIO()
    doc      = _make_doc(buf, A4, 'Ministry of Home Affairs')
    pw       = doc.width
    story    = []

    story += [
        Paragraph("District Occupancy Intelligence Report",
                  _ps('t', fontName='Helvetica-Bold', fontSize=20,
                      textColor=C['primary'], spaceAfter=3, leading=24)),
        Paragraph(f"Generated on: {date_str}     Report ID: {rpt_id}",
                  _ps('s', fontName='Helvetica', fontSize=9,
                      textColor=C['slate_500'], spaceAfter=2)),
        HRFlowable(width='100%', thickness=1, color=C['primary_lt'], spaceAfter=6),
    ]

    tot_p = sum(r['total_people']    for r in data)
    tot_u = sum(r['property_count']  for r in data)
    kd = [[
        [Paragraph("Districts",       _ps('kl', fontName='Helvetica', fontSize=8, textColor=C['slate_500'], alignment=TA_CENTER, spaceAfter=2)),
         Paragraph(str(len(data)),    _ps('kv', fontName='Helvetica-Bold', fontSize=15, textColor=C['primary'], alignment=TA_CENTER, leading=18))],
        [Paragraph("Total Residents", _ps('kl', fontName='Helvetica', fontSize=8, textColor=C['slate_500'], alignment=TA_CENTER, spaceAfter=2)),
         Paragraph(f"{tot_p:,}",      _ps('kv', fontName='Helvetica-Bold', fontSize=15, textColor=C['success'], alignment=TA_CENTER, leading=18))],
        [Paragraph("Total Units",     _ps('kl', fontName='Helvetica', fontSize=8, textColor=C['slate_500'], alignment=TA_CENTER, spaceAfter=2)),
         Paragraph(str(tot_u),        _ps('kv', fontName='Helvetica-Bold', fontSize=15, textColor=C['warning'], alignment=TA_CENTER, leading=18))],
    ]]
    kt = Table(kd, colWidths=[pw/3]*3, rowHeights=[16*mm])
    kt.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,-1),C['slate_50']),
        ('BOX',       (0,0),(-1,-1),0.5,C['slate_200']),
        ('INNERGRID', (0,0),(-1,-1),0.5,C['slate_200']),
        ('VALIGN',    (0,0),(-1,-1),'MIDDLE'),
        ('ALIGN',     (0,0),(-1,-1),'CENTER'),
    ]))
    story += [kt, Spacer(1, 6*mm)]
    story.append(Paragraph("DISTRICT REGISTRY",
        _ps('sec', fontName='Helvetica-Bold', fontSize=8, textColor=C['slate_700'],
            spaceBefore=4, spaceAfter=5, letterSpacing=1)))

    HDR  = ["#","District","Total Residents","Tracked Units","Density Index","Level"]
    rows = [[str(i+1), r['district'], f"{r['total_people']:,}",
             str(r['property_count']),
             f"{min(int(r['total_people']/max(tot_p,1)*100),100)}%",
             r['density']] for i, r in enumerate(data)]
    rows.append(["","TOTALS", f"{tot_p:,}", str(tot_u), "", ""])
    nd = len(rows)-1
    col_w=[10*mm,50*mm,38*mm,32*mm,35*mm,22*mm]
    tbl=Table([HDR]+rows, colWidths=col_w, repeatRows=1)
    tbl.setStyle(TableStyle([
        ('BACKGROUND',   (0,0),(-1,0), C['primary']),
        ('TEXTCOLOR',    (0,0),(-1,0), C['white']),
        ('FONTNAME',     (0,0),(-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',     (0,0),(-1,0), 7.5),
        ('ALIGN',        (0,0),(-1,0), 'CENTER'),
        ('TOPPADDING',   (0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),
        ('LEFTPADDING',  (0,0),(-1,-1),6),('RIGHTPADDING', (0,0),(-1,-1),6),
        ('FONTNAME',     (0,1),(-1,-2),'Helvetica'),('FONTSIZE',(0,1),(-1,-2),8.5),
        ('TEXTCOLOR',    (0,1),(-1,-2),C['slate_700']),
        ('ROWBACKGROUNDS',(0,1),(-1,-2),[C['white'],C['slate_50']]),
        ('LINEBELOW',    (0,0),(-1,-2),0.4,C['slate_200']),
        ('ALIGN',        (2,1),(4,-2),'RIGHT'),
        ('BACKGROUND',   (0,nd+1),(-1,nd+1),C['dark_green']),
        ('TEXTCOLOR',    (0,nd+1),(-1,nd+1),C['white']),
        ('FONTNAME',     (0,nd+1),(-1,nd+1),'Helvetica-Bold'),
        ('ALIGN',        (2,nd+1),(-1,nd+1),'RIGHT'),
        ('LINEABOVE',    (0,nd+1),(-1,nd+1),1.5,C['success']),
        ('VALIGN',       (0,0),(-1,-1),'MIDDLE'),
    ]))
    story.append(tbl)
    doc.build(story, canvasmaker=_NumCanvas)
    buf.seek(0)
    fname = f"Ministry_Occupancy_{NOW().strftime('%Y-%m-%d')}.pdf"
    resp  = HttpResponse(buf, content_type='application/pdf')
    resp['Content-Disposition'] = f'attachment; filename="{fname}"'
    return resp


@require_GET
@login_required
def ministry_export_excel(request):
    data     = _get_ministry_data(request)
    date_str = NOW().strftime('%d %B %Y')
    wb       = openpyxl.Workbook()
    ws       = wb.active
    ws.title = "District Occupancy Report"

    _xl_banner(ws, "District Occupancy Report", "Ministry of Home Affairs", 6, date_str)

    COLS    = ["#","District","Total Residents","Tracked Units","Density Index (%)","Level"]
    HDR_ROW = 4
    _xl_header_row(ws, COLS, HDR_ROW)
    ws.row_dimensions[4].height=28

    tot_p = sum(r['total_people']   for r in data)
    DS    = HDR_ROW + 1
    for ri, r in enumerate(data):
        rn   = DS + ri
        pct  = min(r['total_people']/max(tot_p,1), 1.0)
        fill = HEX['white'] if ri%2==0 else HEX['sl50']
        for ci, val in enumerate([ri+1, r['district'], r['total_people'],
                                   r['property_count'], pct, r['density']], 1):
            c=ws.cell(row=rn,column=ci,value=val)
            c.font=Font(size=9,name='Arial',color=HEX['sl700'])
            c.fill=_solid(fill); c.border=_brd(HEX['sl200'])
            c.alignment=Alignment(horizontal='right' if ci in(3,4,5) else
                                   'center' if ci==1 else 'left', vertical='center')
            if ci==5: c.number_format='0.0%'
        ws.row_dimensions[rn].height=18

    TROW=DS+len(data)
    for ci,(val,align) in enumerate([("","left"),("TOTALS","left"),
        (f'=SUM(C{DS}:C{TROW-1})',"right"),(f'=SUM(D{DS}:D{TROW-1})',"right"),("","center"),("","left")],1):
        c=ws.cell(row=TROW,column=ci,value=val)
        c.font=Font(bold=True,size=9,name='Arial',color=HEX['white'])
        c.fill=_solid(HEX['dark_green']); c.border=_mid_top(HEX['success'])
        c.alignment=Alignment(horizontal=align,vertical='center')
    ws.row_dimensions[TROW].height=20

    for i,w in enumerate([6,28,18,16,18,12],1):
        ws.column_dimensions[get_column_letter(i)].width=w
    ws.freeze_panes=f"A{DS}"; ws.auto_filter.ref=f"A{HDR_ROW}:F{TROW-1}"
    ws.sheet_view.showGridLines=False

    buf=io.BytesIO(); wb.save(buf); buf.seek(0)
    fname=f"Ministry_Occupancy_{NOW().strftime('%Y-%m-%d')}.xlsx"
    resp=HttpResponse(buf,content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    resp['Content-Disposition']=f'attachment; filename="{fname}"'
    return resp


# ══════════════════════════════════════════════════════════════════
# LANDLORD EXPORTS  —  Property Portfolio + Expenses
# ══════════════════════════════════════════════════════════════════

def _get_landlord_data(request):
    # Replace with: Property.objects.filter(owner=request.user)
    return (
        [{"property":"Sunridge Flat 3A","district":"Kabulonga","category":"Residential","price":3500,"status":"Verified"},
         {"property":"Lusaka North Rooms","district":"Northmead","category":"Boarding","price":1200,"status":"Pending"},
         {"property":"Ridgeway Executive Lodge","district":"Ridgeway","category":"Lodge","price":7800,"status":"Verified"},
         {"property":"Chilenje Studio 12","district":"Chilenje","category":"Residential","price":2100,"status":"Pending"}],
        [{"description":"Gate repair","property":"Sunridge Flat 3A","date":"22 Mar 2026","amount":850},
         {"description":"Plumbing work","property":"Sunridge Flat 3A","date":"18 Mar 2026","amount":1300},
         {"description":"Painting","property":"Chilenje Studio 12","date":"10 Mar 2026","amount":2400}],
    )


@require_GET
@login_required
def landlord_export_pdf(request):
    props, expenses = _get_landlord_data(request)
    date_str = NOW().strftime('%d %B %Y')
    buf      = io.BytesIO()
    doc      = _make_doc(buf, A4, 'Owner Dashboard')
    pw       = doc.width
    story    = []

    story += [
        Paragraph("Property Portfolio Report",
                  _ps('t', fontName='Helvetica-Bold', fontSize=20,
                      textColor=C['primary'], spaceAfter=3, leading=24)),
        Paragraph(f"Owner Dashboard Export  |  Generated: {date_str}",
                  _ps('s', fontName='Helvetica', fontSize=9,
                      textColor=C['slate_500'], spaceAfter=2)),
        HRFlowable(width='100%', thickness=1, color=C['primary_lt'], spaceAfter=6),
    ]

    tot_rent = sum(p['price']  for p in props)
    tot_exp  = sum(e['amount'] for e in expenses)
    verified = sum(1 for p in props if p['status']=='Verified')

    kd = [[
        [Paragraph("Properties",      _ps('kl',fontName='Helvetica',fontSize=8,textColor=C['slate_500'],alignment=TA_CENTER,spaceAfter=2)),
         Paragraph(str(len(props)),   _ps('kv',fontName='Helvetica-Bold',fontSize=15,textColor=C['primary'],alignment=TA_CENTER,leading=18))],
        [Paragraph("Monthly Income",  _ps('kl',fontName='Helvetica',fontSize=8,textColor=C['slate_500'],alignment=TA_CENTER,spaceAfter=2)),
         Paragraph(f"ZMW {tot_rent:,.0f}", _ps('kv',fontName='Helvetica-Bold',fontSize=15,textColor=C['success'],alignment=TA_CENTER,leading=18))],
        [Paragraph("Total Expenses",  _ps('kl',fontName='Helvetica',fontSize=8,textColor=C['slate_500'],alignment=TA_CENTER,spaceAfter=2)),
         Paragraph(f"ZMW {tot_exp:,.0f}",  _ps('kv',fontName='Helvetica-Bold',fontSize=15,textColor=C['warning'],alignment=TA_CENTER,leading=18))],
        [Paragraph("Verified",        _ps('kl',fontName='Helvetica',fontSize=8,textColor=C['slate_500'],alignment=TA_CENTER,spaceAfter=2)),
         Paragraph(f"{verified}/{len(props)}", _ps('kv',fontName='Helvetica-Bold',fontSize=15,textColor=C['slate_700'],alignment=TA_CENTER,leading=18))],
    ]]
    kt=Table(kd,colWidths=[pw/4]*4,rowHeights=[16*mm])
    kt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),C['slate_50']),
        ('BOX',(0,0),(-1,-1),0.5,C['slate_200']),('INNERGRID',(0,0),(-1,-1),0.5,C['slate_200']),
        ('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(0,0),(-1,-1),'CENTER')]))
    story += [kt, Spacer(1, 6*mm)]

    story.append(Paragraph("PROPERTY LISTINGS",
        _ps('sec',fontName='Helvetica-Bold',fontSize=8,textColor=C['slate_700'],spaceBefore=4,spaceAfter=5,letterSpacing=1)))
    PHDR=["Property Name","District","Category","Price/mo (ZMW)","Tax Status"]
    prows=[[p['property'],p['district'],p['category'],f"ZMW {p['price']:,.0f}",p['status']] for p in props]
    nd=len(prows)
    prows.append(["","TOTALS","",f"ZMW {tot_rent:,.0f}",""])
    pt=Table([PHDR]+prows,colWidths=[68*mm,32*mm,26*mm,30*mm,24*mm],repeatRows=1)
    pt.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),C['primary']),('TEXTCOLOR',(0,0),(-1,0),C['white']),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,0),7.5),
        ('ALIGN',(0,0),(-1,0),'CENTER'),('TOPPADDING',(0,0),(-1,-1),5),
        ('BOTTOMPADDING',(0,0),(-1,-1),5),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),
        ('FONTNAME',(0,1),(-1,-2),'Helvetica'),('FONTSIZE',(0,1),(-1,-2),8.5),
        ('TEXTCOLOR',(0,1),(-1,-2),C['slate_700']),
        ('ROWBACKGROUNDS',(0,1),(-1,-2),[C['white'],C['slate_50']]),
        ('LINEBELOW',(0,0),(-1,-2),0.4,C['slate_200']),
        ('ALIGN',(3,1),(3,-2),'RIGHT'),
        ('BACKGROUND',(0,nd+1),(-1,nd+1),C['dark_green']),
        ('TEXTCOLOR',(0,nd+1),(-1,nd+1),C['white']),
        ('FONTNAME',(0,nd+1),(-1,nd+1),'Helvetica-Bold'),
        ('ALIGN',(3,nd+1),(3,nd+1),'RIGHT'),
        ('LINEABOVE',(0,nd+1),(-1,nd+1),1.5,C['success']),
        ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
    ]))
    story += [pt, Spacer(1,6*mm)]

    story.append(Paragraph("EXPENSE LEDGER",
        _ps('sec',fontName='Helvetica-Bold',fontSize=8,textColor=C['slate_700'],spaceBefore=4,spaceAfter=5,letterSpacing=1)))
    EHDR=["Description","Property","Date","Amount (ZMW)"]
    erows=[[e['description'],e['property'],e['date'],f"ZMW {e['amount']:,.2f}"] for e in expenses]
    eid=len(erows)
    erows.append(["","TOTALS","",f"ZMW {tot_exp:,.2f}"])
    et=Table([EHDR]+erows,colWidths=[55*mm,55*mm,30*mm,40*mm],repeatRows=1)
    et.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),C['primary']),('TEXTCOLOR',(0,0),(-1,0),C['white']),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,0),7.5),
        ('ALIGN',(0,0),(-1,0),'CENTER'),('TOPPADDING',(0,0),(-1,-1),5),
        ('BOTTOMPADDING',(0,0),(-1,-1),5),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),
        ('FONTNAME',(0,1),(-1,-2),'Helvetica'),('FONTSIZE',(0,1),(-1,-2),8.5),
        ('TEXTCOLOR',(0,1),(-1,-2),C['slate_700']),
        ('ROWBACKGROUNDS',(0,1),(-1,-2),[C['white'],C['slate_50']]),
        ('LINEBELOW',(0,0),(-1,-2),0.4,C['slate_200']),
        ('ALIGN',(3,1),(3,-2),'RIGHT'),('TEXTCOLOR',(3,1),(3,-2),C['warning']),
        ('FONTNAME',(3,1),(3,-2),'Helvetica-Bold'),
        ('BACKGROUND',(0,eid+1),(-1,eid+1),C['dark_green']),
        ('TEXTCOLOR',(0,eid+1),(-1,eid+1),C['white']),
        ('FONTNAME',(0,eid+1),(-1,eid+1),'Helvetica-Bold'),
        ('ALIGN',(3,eid+1),(3,eid+1),'RIGHT'),
        ('LINEABOVE',(0,eid+1),(-1,eid+1),1.5,C['success']),
        ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
    ]))
    story.append(et)
    doc.build(story, canvasmaker=_NumCanvas)
    buf.seek(0)
    fname=f"Landlord_Portfolio_{NOW().strftime('%Y-%m-%d')}.pdf"
    resp=HttpResponse(buf,content_type='application/pdf')
    resp['Content-Disposition']=f'attachment; filename="{fname}"'
    return resp


@require_GET
@login_required
def landlord_export_excel(request):
    props, expenses = _get_landlord_data(request)
    date_str = NOW().strftime('%d %B %Y')
    wb       = openpyxl.Workbook()

    # ── Sheet 1: Properties ──
    ws = wb.active; ws.title="Properties"
    _xl_banner(ws,"Property Portfolio Report","Owner Dashboard",5,date_str)
    PCOLS=["Property Name","District","Category","Price/mo (ZMW)","Tax Status"]
    _xl_header_row(ws,PCOLS,4); ws.row_dimensions[4].height=28
    DS=5
    for ri,p in enumerate(props):
        rn=DS+ri; fill=HEX['white'] if ri%2==0 else HEX['sl50']
        for ci,val in enumerate([p['property'],p['district'],p['category'],p['price'],p['status']],1):
            c=ws.cell(row=rn,column=ci,value=val)
            c.font=Font(size=9,name='Arial',color=HEX['sl700'])
            c.fill=_solid(fill); c.border=_brd(HEX['sl200'])
            c.alignment=Alignment(horizontal='right' if ci==4 else 'left',vertical='center')
            if ci==4: c.number_format='"ZMW "#,##0.00'
        ws.row_dimensions[rn].height=18
    TROW=DS+len(props)
    for ci,(val,align,fmt) in enumerate([("","left",False),("TOTALS","left",False),("","left",False),
        (f'=SUM(D{DS}:D{TROW-1})',"right",True),("","left",False)],1):
        c=ws.cell(row=TROW,column=ci,value=val)
        c.font=Font(bold=True,size=9,name='Arial',color=HEX['white'])
        c.fill=_solid(HEX['dark_green']); c.border=_mid_top(HEX['success'])
        c.alignment=Alignment(horizontal=align,vertical='center')
        if fmt: c.number_format='"ZMW "#,##0.00'
    ws.row_dimensions[TROW].height=20
    for i,w in enumerate([36,18,16,20,14],1): ws.column_dimensions[get_column_letter(i)].width=w
    ws.freeze_panes=f"A{DS}"; ws.auto_filter.ref=f"A4:E{TROW-1}"
    ws.sheet_view.showGridLines=False

    # ── Sheet 2: Expenses ──
    we=wb.create_sheet("Expenses")
    _xl_banner(we,"Expense Ledger","Owner Dashboard",4,date_str)
    ECOLS=["Description","Property","Date","Amount (ZMW)"]
    _xl_header_row(we,ECOLS,4); we.row_dimensions[4].height=28
    DS2=5
    for ri,e in enumerate(expenses):
        rn=DS2+ri; fill=HEX['white'] if ri%2==0 else HEX['sl50']
        for ci,val in enumerate([e['description'],e['property'],e['date'],e['amount']],1):
            c=we.cell(row=rn,column=ci,value=val)
            c.font=Font(size=9,name='Arial',color=HEX['sl700'])
            c.fill=_solid(fill); c.border=_brd(HEX['sl200'])
            c.alignment=Alignment(horizontal='right' if ci==4 else 'left',vertical='center')
            if ci==4: c.font=Font(size=9,name='Arial',color=HEX['warning'],bold=True); c.number_format='"ZMW "#,##0.00'
        we.row_dimensions[rn].height=18
    TROW2=DS2+len(expenses)
    for ci,(val,align,fmt) in enumerate([("","l",False),("TOTALS","left",False),("","left",False),
        (f'=SUM(D{DS2}:D{TROW2-1})',"right",True)],1):
        c=we.cell(row=TROW2,column=ci,value=val)
        c.font=Font(bold=True,size=9,name='Arial',color=HEX['white'])
        c.fill=_solid(HEX['dark_green']); c.border=_mid_top(HEX['success'])
        c.alignment=Alignment(horizontal=align,vertical='center')
        if fmt: c.number_format='"ZMW "#,##0.00'
    we.row_dimensions[TROW2].height=20
    for i,w in enumerate([30,28,16,20],1): we.column_dimensions[get_column_letter(i)].width=w
    we.freeze_panes=f"A{DS2}"; we.auto_filter.ref=f"A4:D{TROW2-1}"
    we.sheet_view.showGridLines=False

    buf=io.BytesIO(); wb.save(buf); buf.seek(0)
    fname=f"Landlord_Portfolio_{NOW().strftime('%Y-%m-%d')}.xlsx"
    resp=HttpResponse(buf,content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    resp['Content-Disposition']=f'attachment; filename="{fname}"'
    return resp


# ---------------------------------------------------------------
# HELPER: Resolve the real user from token (cookie or header)
# This bypasses Django's unreliable session-based request.user
# ---------------------------------------------------------------
def get_user_from_request(request):
    # 1. Try Authorization header
    auth_header = request.META.get('HTTP_AUTHORIZATION', '')
    if auth_header.startswith('Token '):
        token_key = auth_header.split(' ')[1]
        try:
            return Token.objects.get(key=token_key).user
        except Token.DoesNotExist:
            pass

    # 2. Try auth_token cookie
    token_key = request.COOKIES.get('auth_token')
    if token_key:
        try:
            return Token.objects.get(key=token_key).user
        except Token.DoesNotExist:
            pass

    return None  # Not authenticated


# ---------------------------------------------------------------
# FRONTEND VIEWS
# ---------------------------------------------------------------

def index_page(request):
    return render(request, 'index.html')


def auth_page(request):
    return render(request, 'auth.html')


def property_detail_page(request, pk):
    property_obj = get_object_or_404(Property, pk=pk)
    landlord_phone = property_obj.owner.phone_number
    return render(request, 'property_detail.html', {
        'property': property_obj,
        'landlord_phone': landlord_phone,
    })


def apply_page(request, pk):
    user = get_user_from_request(request)
    if not user:
        return redirect('/auth/login/')
    property_obj = get_object_or_404(Property, pk=pk)
    return render(request, 'apply.html', {'property': property_obj})


def add_property_page(request):
    user = get_user_from_request(request)
    if not user:
        return redirect('/auth/login/')
    return render(request, 'add_property.html')


def dashboard_page(request):
    """Landlord dashboard."""
    user = get_user_from_request(request)
    if not user:
        return redirect('/auth/login/')

    user_properties = Property.objects.filter(owner=user)
    total_tax = sum(p.estimated_annual_tax() for p in user_properties)

    return render(request, 'dashboard.html', {
        'properties': user_properties,
        'user_properties': user_properties,
        'total_tax': total_tax,
        'property_count': user_properties.count(),
    })


def zra_dashboard_page(request):
    """ZRA Tax Compliance dashboard."""
    user = get_user_from_request(request)
    if not user:
        return redirect('/auth/login/')
    if user.user_type != 'ZRA':
        return render(request, '403.html')

    all_properties = Property.objects.all()
    total_tax = sum(p.estimated_annual_tax() for p in all_properties)
    compliant_count = all_properties.filter(is_tax_compliant=True).count()
    non_compliant_count = all_properties.filter(is_tax_compliant=False).count()
    total_count = all_properties.count()

    return render(request, 'zra_dashboard.html', {
        'total_tax': total_tax,
        'compliance_rate': (compliant_count / total_count * 100) if total_count > 0 else 0,
        'non_compliant_count': non_compliant_count,
    })


def occupancy_dashboard_page(request):
    """Ministry of Home Affairs dashboard."""
    user = get_user_from_request(request)
    if not user:
        return redirect('/auth/login/')
    if user.user_type != 'MINISTRY':
        return render(request, '403.html')

    occupancy_stats = (
        RentalAgreement.objects.filter(is_active=True)
        .values('property__district')
        .annotate(
            total_people=Sum('number_of_occupants'),
            property_count=Count('property', distinct=True)
        )
        .order_by('-total_people')
    )

    return render(request, 'ministry_dashboard.html', {
        'occupancy_stats': occupancy_stats,
    })


# ---------------------------------------------------------------
# API VIEWSETS
# ---------------------------------------------------------------

class PropertyViewSet(viewsets.ModelViewSet):
    queryset = Property.objects.all()
    serializer_class = PropertySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get_queryset(self):
        queryset = Property.objects.all()
        
        # Add dynamic filtering
        status = self.request.query_params.get('status')
        search = self.request.query_params.get('search')

        if status == 'pending':
            queryset = queryset.filter(is_tax_compliant=False)
        elif status == 'compliant':
            queryset = queryset.filter(is_tax_compliant=True)

        if search:
            queryset = queryset.filter(
                Q(title__icontains=search) | 
                Q(owner__full_name__icontains=search) |
                Q(owner__username__icontains=search) |
                Q(owner__tpin_number__icontains=search) |
                Q(owner__nrc_number__icontains=search) |
                Q(id__icontains=search)
            )
        return queryset

    def perform_create(self, serializer):
        property_obj = serializer.save(owner=self.request.user)
        images = self.request.FILES.getlist('images')
        captions = self.request.POST.getlist('captions')
        try:
            main_index = int(self.request.POST.get('main_image_index', '0'))
        except ValueError:
            main_index = 0

        from .models import PropertyImage
        for i, image in enumerate(images):
            PropertyImage.objects.create(
                property=property_obj,
                image=image,
                caption=captions[i] if i < len(captions) else '',
                is_main=(i == main_index)
            )

    @action(detail=True, methods=['post'], permission_classes=[permissions.IsAuthenticated])
    def toggle_compliance(self, request, pk=None):
        if request.user.user_type != 'ZRA':
            return Response({'error': 'Unauthorized'}, status=status.HTTP_403_FORBIDDEN)
        property_obj = self.get_object()
        property_obj.is_tax_compliant = not property_obj.is_tax_compliant
        property_obj.save()
        return Response({'is_tax_compliant': property_obj.is_tax_compliant})

    @action(detail=False, methods=['get'], permission_classes=[permissions.IsAuthenticated])
    def zra_report(self, request):
        if request.user.user_type != 'ZRA':
            return Response({'error': 'Unauthorized'}, status=403)
        landlords = User.objects.filter(user_type='LANDLORD')
        stats = []
        for landlord in landlords:
            props = Property.objects.filter(owner=landlord)
            stats.append({
                'landlord_name': landlord.username,
                'property_count': props.count(),
                'annual_income_estimate': sum(float(p.price) * 12 for p in props)
            })
        return Response({'landlords': stats})

    @action(detail=False, methods=['get'], permission_classes=[permissions.IsAuthenticated])
    def census_report(self, request):
        if request.user.user_type != 'MINISTRY':
            return Response({'error': 'Unauthorized'}, status=403)
        agreements = RentalAgreement.objects.filter(is_active=True)
        stats = {}
        for ag in agreements:
            dist = ag.property.district
            if dist not in stats:
                stats[dist] = {'total_population': 0, 'property_count': 0, 'by_category': {}}
            stats[dist]['total_population'] += ag.number_of_occupants
            stats[dist]['property_count'] += 1
            cat = ag.property.category
            stats[dist]['by_category'][cat] = stats[dist]['by_category'].get(cat, 0) + ag.number_of_occupants
        return Response(stats)


class RentalAgreementViewSet(viewsets.ModelViewSet):
    queryset = RentalAgreement.objects.all()
    serializer_class = RentalAgreementSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.user_type == 'TENANT':
            return RentalAgreement.objects.filter(tenant=user)
        elif user.user_type == 'LANDLORD':
            return RentalAgreement.objects.filter(property__owner=user)
        return RentalAgreement.objects.all()

    def perform_create(self, serializer):
        serializer.save(tenant=self.request.user)

    @action(detail=True, methods=['post'], permission_classes=[permissions.IsAuthenticated])
    def approve(self, request, pk=None):
        agreement = self.get_object()
        if agreement.property.owner != request.user:
            return Response({'error': 'Unauthorized'}, status=status.HTTP_403_FORBIDDEN)
        agreement.status = 'APPROVED'
        agreement.save()
        return Response({'status': 'Approved'})

    @action(detail=True, methods=['post'], permission_classes=[permissions.IsAuthenticated])
    def reject(self, request, pk=None):
        agreement = self.get_object()
        if agreement.property.owner != request.user:
            return Response({'error': 'Unauthorized'}, status=status.HTTP_403_FORBIDDEN)
        agreement.status = 'REJECTED'
        agreement.save()
        return Response({'status': 'Rejected'})


class ExpenseViewSet(viewsets.ModelViewSet):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Expense.objects.filter(property__owner=self.request.user)

    def perform_create(self, serializer):
        property_id = self.request.data.get('property')
        prop = get_object_or_404(Property, id=property_id)
        if prop.owner != self.request.user:
            raise permissions.PermissionDenied("You don't own this property.")
        serializer.save()

def password_reset_confirm_page(request):
    """
    Serves the password-reset confirm HTML page.
    The page reads uid + token from the URL query string via JS
    and POSTs to /auth/password-reset/confirm/ API endpoint.
    """
    return render(request, 'password_reset_confirm.html')